default:
  default_key: "default_value"

staging:
  ontologyFileID: syn52050046
  parquetDirID: syn59800646
  # dataset_name_filter: !expr c("fitbit","healthkit")
  deleteExistingDir: FALSE
  concept_replacements: !expr c("mins" = "minutes",
                                "avghr" = "averageheartrate",
                                "spo2" = "spo2_",
                                "hrv" = "hrv_dailyrmssd",
                                "restinghr" = "restingheartrate",
                                "sleepbrth" = "sleepsummarybreath",
                                "sleepstarttime" = "startdate",
                                "sleependtime" = "enddate")
  concept_filter_col: CONCEPT_CD
  synFolderID: syn52504335
  # method: sts
  s3bucket: recover-main-project
  s3basekey: main/archive/2024-05-21/
  downloadLocation: ./temp-parquet
  selectedVarsFileID: syn53503994
  outputConceptsDir: ./temp-output-concepts

prod:
  inherits: staging
  synFolderID: syn51406700
